name: Tests

on:
  # if pushed directly to the master
  push:
#    branches:
#      - master
  # on a pull request
  pull_request:
    branches:
      - master

jobs:
  # Run unit tests and submit Coverage Report
  unit-test:
    name: Standard Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check

      - name: Build Coverage Report
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: coverageReport

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/coverageReport/coverageReport.xml

  # Run tests for java 8 targets
  java8-test:
    name: Java 8 Test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: checkJava8

  # Make sure it works with all standard JVMs on main OSes
  platform-test:
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    continue-on-error: ${{ matrix.java != '11' }}
    strategy:
      matrix:
        java: ["11", "12", "13", "14"]
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          # see https://github.com/eskatos/gradle-command-action/issues/24
          wrapper-cache-enabled: false
          arguments: check

  #Test with android emulators provided
  android-platform-test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [24, 25, 26, 27, 28, 29, 30]
        arch: [x86_64, x86]
        include:
         - api-level: 30
           arch: arm64-v8a
           target: google_apis
        exclude:
          - api-level: 30
            arch: x86
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        run: ./cargo_ndk_prep.sh; touch local.properties

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
#          ndk: 21.4.7075529 ## This would install the NDK version, but it's already installed in the image.
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          script: ./gradlew connectedCheck

  # Formatter may behave differently on different locales, makes sure tests are not failing
  locale-test:
    name: Locale ${{ matrix.locale }}
    continue-on-error: true
    strategy:
      matrix:
        locale: ["ru_RU.UTF-8", "de_DE.UTF-8", "de_CH.UTF-8", "zh_CN.UTF-8"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        run: ./cargo_ndk_prep.sh

      - name: Set Locale
        run: |
          sudo locale-gen ${{ matrix.locale }}
          sudo update-locale LANG=${{ matrix.locale }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
        env:
          LANG: ${{ matrix.locale }}